def cleanup(text):
    text=text.replace('ã', 'a')
    text=text.replace('â', 'a')
    text=text.replace('á', 'a')
    text=text.replace('à', 'a')
    text=text.replace('é', 'e')
    text=text.replace('è', 'e')
    text=text.replace('ê', 'e')
    text=text.replace('î', 'i')
    text=text.replace('í', 'i')
    text=text.replace('ì', 'i')
    text=text.replace('ó', 'o')
    text=text.replace('ò', 'o')
    text=text.replace('õ', 'o')
    text=text.replace('ô', 'o')
    text=text.replace('ú', 'u')
    text=text.replace('ù', 'a')
    text=text.replace(' ', '_')
    text=text.lower()
    return text